name: ROS2

on:
  pull_request:
    branches: [ master ]
    paths-ignore: '**.md'
  push:
    branches: [ master ]
    paths-ignore: '**.md'
  repository_dispatch:
    types: [trigger-event]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Docker login
        continue-on-error: true
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          tags: koide3/glim_ext:humble
          file: ${{github.workspace}}/glim_ext/docker/Dockerfile.ros2
          context: .
          push: false

